import { Component, OnInit } from '@angular/core';
import { ManageCftService } from '../../../services/manage-cft.service';
import { CFTDetailsModel } from '../../../@core/models/cftdetails.model';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'ngx-view-cft',
  templateUrl: './view-cft.component.html',
  styleUrls: ['./view-cft.component.scss']
})


export class ViewCftComponent implements OnInit {
  cftDData: CFTDetailsModel[];
  searchTerm: string;
  constructor(private activeRoute: ActivatedRoute, private router: Router, private managecftservice: ManageCftService) {

  }
  EditCft(item) {
    this.managecftservice.setCFTRecordStateForEdit(item).subscribe(data => {
      this.router.navigate(['../modify-cft'], { relativeTo: this.activeRoute });
    })
  }
  ngOnInit() {
    this.managecftservice.getAllCFTDetails().subscribe(Data => {
      this.cftDData = Data;
    })
    // this.cftDData = this.dummyData;
    // console.log(JSON.stringify(this.cftDData));
  }

  // dummyData: Array<CFTDetailsModel> = [
  //   {
  //     "continent": "ASIA",
  //     "country": "THAILAND",
  //     "distributor": "Yanmar SP Co. LTD  ",
  //     "distributorCode": "2000371",
  //     "dealer": "Ngaunhonglee Agricultural Machinery Co.,Ltd. ",
  //     "dealerCode": "2000371D2",
  //     "scrRelated": "PRODUCT FAILURE",
  //     "seviority": "Very High",
  //     "tractorStatus": "NULL",
  //     "tractorOffRoad": "NO",
  //     "statusAstDistributorEnd": "CLOSE",
  //     "reapeatComplaint": "NO",
  //     "scrNo": "SCR-2000371-2018-201",
  //     "scrDate": "2-Oct-18",
  //     "uploadedDate": "10/2/18 7:38",
  //     "complaint": " battery deteriorates.",
  //     "areaofOperation": "NULL",
  //     "attachment": "NULL",
  //     "aggregate": "NULL",
  //     "subAggregate": "NULL",
  //     "modelName": "SOLIS 26 4WD FL",
  //     "scr_ChassisNo": "AMKSG722543G26",
  //     "engineNo": "A14443B8",
  //     "dateOfSale": "30-Nov-18",
  //     "hoursWorked": 5,
  //     "failureDate": "13-Sep-18",
  //     "observation": "battery deteriorates",
  //     "dealerAction": "Make a request for approval and take the spare parts to the store.",
  //     "rcabyServieTeam": "Tractor parked at dealer showroom and after 1 month try to start and found battery discharged.  Tried to recharge the battery but it can not charge...",
  //     "complaintStatusByServiceTeam": "Request",
  //     "scr_SCRCode": "NULL",
  //     "targetDate": null,
  //     "cftCreationDate": null,
  //     "cftCategoryType": null,
  //     "revisedDate": new Date(),
  //     "revisionNo": 123123,
  //     "revisedBy": "Himanshi",
  //     "approvedBy": "Himanshi",
  //     "createdBy": "Himanshi",
  //     "cftNO": null
  //   },
  //   {
  //     "continent": "Africa",
  //     "country": "THAILAND",
  //     "distributor": "Yanmar SP Co. LTD  ",
  //     "distributorCode": "2000371",
  //     "dealer": "T.T. First Tractor Co.,Ltd. ",
  //     "dealerCode": "2000371D3",
  //     "scrRelated": "PRODUCT FAILURE",
  //     "seviority": "Very High",
  //     "tractorStatus": "DELIVERD TO CUSTOMER",
  //     "tractorOffRoad": "YES",
  //     "statusAstDistributorEnd": "CLOSE",
  //     "reapeatComplaint": "NO",
  //     "scrNo": "SCR-2000371-2019-9",
  //     "scrDate": "10-Feb-19",
  //     "uploadedDate": "2/10/19 9:57",
  //     "complaint": "Clutch system has problems.(There is a loud color at the clutch room)",
  //     "areaofOperation": "NULL",
  //     "attachment": "NULL",
  //     "aggregate": "NULL",
  //     "subAggregate": "NULL",
  //     "modelName": "SOLIS 26 4WD FL",
  //     "scr_ChassisNo": "AMKSG722544G26",
  //     "engineNo": "A14391B8",
  //     "dateOfSale": "14-Jun-18",
  //     "hoursWorked": 83,
  //     "failureDate": "11-Nov-18",
  //     "observation": "Clutch system has problems.(There is a loud color at the clutch room)",
  //     "dealerAction": "Make corrections and replace damaged parts for customers",
  //     "rcabyServieTeam": "-Customer heard abnormal noise during Field operations.  -Technician  checked by de-press the clutch pedal  and found noise occurred. (All gears)  - Technician checked the Clutch parts are normal condition.    -Damaged parts 20004297AB,10056631AA  Refer t",
  //     "complaintStatusByServiceTeam": "Request",
  //     "scr_SCRCode": "NULL",
  //     "targetDate": null,
  //     "cftCreationDate": null,
  //     "cftCategoryType": null,
  //     "revisedDate": new Date(),
  //     "revisionNo": 123123,
  //     "revisedBy": "Himanshi",
  //     "approvedBy": "Himanshi",
  //     "createdBy": "Himanshi",
  //     "cftNO": null
  //   },
  //   {
  //     "continent": "ASIA",
  //     "country": "THAILAND",
  //     "distributor": "Yanmar SP Co. LTD  ",
  //     "distributorCode": "2000371",
  //     "dealer": "T.T. First Tractor Co.,Ltd. ",
  //     "dealerCode": "2000371D3",
  //     "scrRelated": "PRODUCT FAILURE",
  //     "seviority": "Very High",
  //     "tractorStatus": "DELIVERD TO CUSTOMER",
  //     "tractorOffRoad": "NO",
  //     "statusAstDistributorEnd": "OPEN",
  //     "reapeatComplaint": "YES",
  //     "scrNo": "SCR-2000371-2019-60",
  //     "scrDate": "22-Mar-19",
  //     "uploadedDate": "3/22/19 13:12",
  //     "complaint": "Noisy in the gear room",
  //     "areaofOperation": "NULL",
  //     "attachment": "NULL",
  //     "aggregate": "NULL",
  //     "subAggregate": "NULL",
  //     "modelName": "SOLIS 26 4WD FL",
  //     "scr_ChassisNo": "AMKSG722544G26",
  //     "engineNo": "A14391B8",
  //     "dateOfSale": "14-Jun-18",
  //     "hoursWorked": 125,
  //     "failureDate": "12-Mar-19",
  //     "observation": "Noisy in the gear room",
  //     "dealerAction": "Meet the customer to request the car to return and check. The customer will bring the backup car to use before, but the customer does not agree and want to change the new car.                 ",
  //     "rcabyServieTeam": "This Tractor was reported at 83 HMR for Input shaft bearing failure.   After replace the Input shaft and bearing Tractor start working normally.  Now again on 125 HMR the Abnormal noise started form Transmission .",
  //     "complaintStatusByServiceTeam": "Request",
  //     "scr_SCRCode": "NULL",
  //     "targetDate": null,
  //     "cftCreationDate": null,
  //     "cftCategoryType": null,
  //     "revisedDate": new Date(),
  //     "revisionNo": 123123,
  //     "revisedBy": "Himanshi",
  //     "approvedBy": "Himanshi",
  //     "createdBy": "Himanshi",
  //     "cftNO": null
  //   },
  //   {
  //     "continent": "Europe",
  //     "country": "THAILAND",
  //     "distributor": "Yanmar SP Co. LTD  ",
  //     "distributorCode": "2000371",
  //     "dealer": "YANMAR TRACTOR UTHAITANI PARTNERSHIP LTD ",
  //     "dealerCode": "WM116010",
  //     "scrRelated": "PRODUCT FAILURE",
  //     "seviority": "Very High",
  //     "tractorStatus": "DEALER STOCK",
  //     "dateOfSale": "14-Jun-18",
  //     "tractorOffRoad": "NO",
  //     "statusAstDistributorEnd": "CLOSE",
  //     "reapeatComplaint": "NO",
  //     "scrNo": "SCR-2000371-2019-61",
  //     "scrDate": "25-Mar-19",
  //     "uploadedDate": "3/25/19 10:06",
  //     "complaint": "Oil line, forced cylinder, leak",
  //     "areaofOperation": "NULL",
  //     "attachment": "NULL",
  //     "aggregate": "NULL",
  //     "subAggregate": "NULL",
  //     "modelName": "SOLIS 26 4WD FL",
  //     "scr_ChassisNo": "AMKSG722546G26",
  //     "engineNo": "A13591M7",
  //     "hoursWorked": 6,
  //     "failureDate": "25-Feb-19",
  //     "observation": "Oil line, forced cylinder, leak",
  //     "dealerAction": "Make changes to spare parts for customers",
  //     "rcabyServieTeam": "Action already taken against this issue. 100% Supply of pipes is after double checking the pressure. ",
  //     "complaintStatusByServiceTeam": "NULL",
  //     "scr_SCRCode": "NULL",
  //     "targetDate": null,
  //     "cftCreationDate": null,
  //     "cftCategoryType": null,
  //     "revisedDate": new Date(),
  //     "revisionNo": 123123,
  //     "revisedBy": "Himanshi",
  //     "approvedBy": "Himanshi",
  //     "createdBy": "Himanshi",
  //     "cftNO": null
  //   },
  //   {
  //     "continent": "North America",
  //     "country": "THAILAND",
  //     "distributor": "Yanmar SP Co. LTD  ",
  //     "distributorCode": "2000371",
  //     "dealer": "YANMAR TRACTOR UTHAITANI PARTNERSHIP LTD ",
  //     "dealerCode": "WM116010",
  //     "scrRelated": "PRODUCT FAILURE",
  //     "seviority": "Very High",
  //     "tractorStatus": "DEALER STOCK",
  //     "tractorOffRoad": "NO",
  //     "statusAstDistributorEnd": "OPEN",
  //     "reapeatComplaint": "NO",
  //     "scrNo": "SCR-2000371-2019-165",
  //     "scrDate": "30-May-19",
  //     "uploadedDate": "5/30/19 18:03",
  //     "complaint": "Enter the PDI check (the rubber bonnet deteriorates)",
  //     "areaofOperation": "NULL",
  //     "attachment": "NULL",
  //     "aggregate": "NULL",
  //     "subAggregate": "NULL",
  //     "modelName": "SOLIS 26 4WD FL",
  //     "scr_ChassisNo": "AMKSG722546G26",
  //     "engineNo": "A13591M7",
  //     "dateOfSale": "14-Jun-18",
  //     "hoursWorked": 7,
  //     "failureDate": "15-May-19",
  //     "observation": "Enter the PDI check (the rubber bonnet deteriorates)",
  //     "dealerAction": "Making a proposal for approval and withdrawing spare parts",
  //     "rcabyServieTeam": "This Rubber damaged. It may be happen during other local attachment fitment. ",
  //     "complaintStatusByServiceTeam": "NULL",
  //     "scr_SCRCode": "NULL",
  //     "targetDate": null,
  //     "cftCreationDate": null,
  //     "cftCategoryType": null,
  //     "revisedDate": new Date(),
  //     "revisionNo": 123123,
  //     "revisedBy": "Himanshi",
  //     "approvedBy": "Himanshi",
  //     "createdBy": "Himanshi",
  //     "cftNO": null
  //   },
  //   {
  //     "continent": "South America",
  //     "country": "THAILAND",
  //     "distributor": "Yanmar SP Co. LTD  ",
  //     "distributorCode": "2000371",
  //     "dealer": "YANMAR TRACTOR UTHAITANI PARTNERSHIP LTD ",
  //     "dealerCode": "WM116010",
  //     "dateOfSale": "14-Jun-18",
  //     "scrRelated": "PRODUCT FAILURE",
  //     "seviority": "Very High",
  //     "tractorStatus": "DEALER STOCK",
  //     "tractorOffRoad": "NO",
  //     "statusAstDistributorEnd": "OPEN",
  //     "reapeatComplaint": "NO",
  //     "scrNo": "SCR-2000371-2019-165",
  //     "scrDate": "30-May-19",
  //     "uploadedDate": "5/30/19 18:03",
  //     "complaint": "Enter the PDI check (the rubber bonnet deteriorates)",
  //     "areaofOperation": "NULL",
  //     "attachment": "NULL",
  //     "aggregate": "NULL",
  //     "subAggregate": "NULL",
  //     "modelName": "SOLIS 26 4WD FL",
  //     "scr_ChassisNo": "AMKSG722546G26",
  //     "engineNo": "A13591M7",
  //     "hoursWorked": 7,
  //     "failureDate": "15-May-19",
  //     "observation": "Enter the PDI check (the rubber bonnet deteriorates)",
  //     "dealerAction": "Making a proposal for approval and withdrawing spare parts",
  //     "rcabyServieTeam": "This Rubber damaged. It may be happen during other local attachment fitment. ",
  //     "complaintStatusByServiceTeam": "NULL",
  //     "scr_SCRCode": "NULL",
  //     "targetDate": null,
  //     "cftCreationDate": null,
  //     "cftCategoryType": null,
  //     "revisedDate": new Date(),
  //     "revisionNo": 123123,
  //     "revisedBy": "Himanshi",
  //     "approvedBy": "Himanshi",
  //     "createdBy": "Himanshi",
  //     "cftNO": null
  //   }
  // ]

}

